import { argv, cwd } from "process";
import { resolve } from "path";
import { pathToFileURL } from "url";
import yargs from "yargs";
import { hideBin } from "yargs/helpers";
import { ESBenchHost, report } from "./host.js";
import { ESBenchConfig } from "./config.js";

process.title = "node (esbench)";

async function loadConfig(path?: string) {
	let url = resolve(cwd(), path ?? "esbench.config.js");
	url = pathToFileURL(url).toString();
	try {
		return (await import(url)).default;
	} catch (e) {
		if (path || e.code !== "ERR_MODULE_NOT_FOUND") {
			throw e;
		}
		return {} as ESBenchConfig;
	}
}

const program = yargs(hideBin(argv))
	.command("report <file>", "Generate report from results", {
		config: {
			type: "string",
			description: "Use specified config file",
		},
		file: {
			type: "string",
			description: "Result file generated by rawReporter to load",
			demandOption: true,
		},
	}, async args => {
		const { config, file } = args;
		return report(await loadConfig(config), file);
	})
	.command("*", "Run benchmark", {
		config: {
			type: "string",
			description: "Use specified config file",
			default: "esbench.config.js",
		},
		file: {
			type: "string",
			description: "Run only benchmark for specified file",
		},
		name: {
			type: "string",
			description: "Run benchmark with names matching the Regex pattern",
		},
	}, async args => {
		const { config, file, name = "" } = args;
		return new ESBenchHost(await loadConfig(config)).run(file, new RegExp(name));
	});

program.version(false).strict().parseAsync();
