import { Awaitable, identity } from "@kaciras/utilities/node";
import { ESBenchResult } from "./client/summary.js";
import { Builder, Executor } from "./toolchain.js";
import noBuild from "./builder/default.js";
import DirectExecutor from "./executor/direct.js";
import textReporter from "./reporter/text.js";

/**
 * You can assign a name for a tool (builder or executor). Each tool can only have one name.
 *
 * @example
 * export default defineConfig({
 *   toolchains: [{
 *     builders: [
 *       new ViteBuilder({ build: { minify: false } }),
 *       {
 *           name: "Vite Minified"
 *           use: new ViteBuilder({ build: { minify: true } }),
 *       }
 *     ]
 *   }]
 * });
 */
export type Nameable<T> = T | { name: string; use: T };

export interface ToolchainOptions {
	/**
	 * The micromatch glob patterns ESBench uses to detect suite files.
	 *
	 * By default, match all JS/TS files in the ./benchmark folder.
	 */
	include?: string[];

	/**
	 * Specific a list of builder to transform source files before execution.
	 * Each build results as a new set of benchmarks.
	 *
	 * By default, it will perform no transform at all.
	 */
	builders?: Array<Nameable<Builder>>;

	/**
	 * With executors, you specify JS runtimes that ESBench execute your suites.
	 *
	 * By default, ESBench run your suites in the current process.
	 */
	executors?: Array<Nameable<Executor>>;
}

/**
 * A reporter allows you to export results of your benchmark in different formats.
 *
 * @param result
 * @param prev Another result used to calculate difference.
 */
export type Reporter = (result: ESBenchResult, prev?: ESBenchResult) => Awaitable<unknown>;

export interface ESBenchConfig {
	/**
	 * Which files will be run as benchmark suites uses which toolchains.
	 */
	toolchains?: ToolchainOptions[];

	/**
	 * Choose dir that ESBench uses for mutation testing.
	 *
	 * @default ".esbench-tmp"
	 */
	tempDir?: string;

	/**
	 * Choose whether or not to clean temporary files.
	 *
	 * @default true
	 */
	cleanTempDir?: boolean;

	/**
	 * Specifies the path to a result file generated by rawReporter. If it exists,
	 * the difference between the current result and it will be displayed on the report.
	 */
	diff?: string;

	/**
	 * Configure reporters for processing benchmark results.
	 *
	 * @default [textReporter()]
	 */
	reporters?: Reporter[];
}

/**
 * Type helper to mark the object as an ESBench config.
 */
export const defineConfig = identity<ESBenchConfig>;

export type NormalizedConfig = Required<ESBenchConfig> & {
	toolchains: Array<Required<ToolchainOptions>>;
}

export function normalizeConfig(input: ESBenchConfig) {
	if (input.toolchains?.length === 0) {
		throw new Error("No toolchains.");
	}

	const config: ESBenchConfig = {
		tempDir: ".esbench-tmp",
		cleanTempDir: true,
		reporters: [textReporter()],
		...input,
		toolchains: [],
	};

	for (let toolchain of input.toolchains ?? [{}]) {
		toolchain = {
			include: ["./benchmark/**/*.[jt]s?(x)"],
			builders: [noBuild],
			executors: [new DirectExecutor()],
			...toolchain,
		};
		config.toolchains!.push(toolchain);

		if (toolchain.builders?.length === 0) {
			throw new Error("No builders.");
		}
		if (toolchain.executors!.length === 0) {
			throw new Error("No executors.");
		}
		if (toolchain.include?.length === 0) {
			throw new Error("No included files.");
		}
	}

	return config as NormalizedConfig;
}
