import nodeModule from "module";
import { argv } from "process";
import { importCWD } from "@kaciras/utilities/node";
import yargs from "yargs";
import { hideBin } from "yargs/helpers";
import { report, start } from "./host.js";

const DEFAULT_CONFIG_FILE = "esbench.config.js";

process.title = "node (esbench)";

nodeModule.register?.("./loader.js", import.meta.url);

const program = yargs(hideBin(argv))
	.command("report <files...>", "Generate report from result files", {
		config: {
			type: "string",
			description: "Use specified config file",
			default: DEFAULT_CONFIG_FILE,
		},
		files: {
			type: "string",
			description: "Result files generated by rawReporter to load",
			array: true,
			demandOption: true,
		},
	}, async args => {
		const { config, files } = args;
		const cfgObj = await importCWD(config, DEFAULT_CONFIG_FILE);
		return report(cfgObj ?? {}, files);
	})
	.command("*", "Run benchmark", {
		config: {
			type: "string",
			description: "Use specified config file",
			default: DEFAULT_CONFIG_FILE,
		},
		file: {
			type: "string",
			description: "Run only suites that contains the value in their paths",
		},
		builder: {
			type: "string",
			description: "Run only suites built with the specified builder which name matching the Regex pattern",
		},
		executor: {
			type: "string",
			description: "Run only suites executed with the specified executor which name matching the Regex pattern",
		},
		name: {
			type: "string",
			description: "Run benchmark with names matching the Regex pattern",
		},
		shared: {
			type: "string",
			description: "Execute suites in a specified shard",
		},
	}, async args => {
		const { config, ...filter } = args;
		const cfgObj = await importCWD(config, DEFAULT_CONFIG_FILE);
		return start(cfgObj ?? {}, filter);
	});

program.version(false).strict().showHelpOnFail(false).parseAsync();
