import nodeModule from "module";
import { argv } from "process";
import { importCWD } from "@kaciras/utilities/node";
import yargs from "yargs";
import { hideBin } from "yargs/helpers";
import { report, start } from "./commands.js";

const DEFAULT_CONFIG_FILE = "esbench.config.js";

process.title = "node (esbench)";

const program = yargs(hideBin(argv))
	.command("report <files...>", "Generate report from result files", {
		config: {
			type: "string",
			description: "Use specified config file",
			default: DEFAULT_CONFIG_FILE,
		},
		noLoader: {
			type: "boolean",
			description: "Disable builtin TypeScript loader",
			default: false,
		},
		files: {
			type: "string",
			description: "Result files generated by rawReporter to load",
			array: true,
			demandOption: true,
		},
	}, async args => {
		const { config, files } = args;
		if (!args.noLoader) {
			nodeModule.register?.("./loader.js", import.meta.url);
		}
		const cfgObj = await importCWD(config, DEFAULT_CONFIG_FILE);
		return report(cfgObj ?? {}, files);
	})
	.command("*", "Run benchmark", {
		config: {
			type: "string",
			description: "Use specified config file",
			default: DEFAULT_CONFIG_FILE,
		},
		noLoader: {
			type: "boolean",
			description: "Disable builtin TypeScript loader",
			default: false,
		},
		logLevel: {
			type: "string",
			description: "Log level (debug | info | warn | error | off)",
		},
		file: {
			type: "string",
			description: "Run only suites that contains the value in their paths",
		},
		builder: {
			type: "string",
			description: "Run only suites built with the specified builder which name matching the Regex pattern",
		},
		executor: {
			type: "string",
			description: "Run only suites executed with the specified executor which name matching the Regex pattern",
		},
		name: {
			type: "string",
			description: "Run benchmark with names matching the Regex pattern",
		},
		shared: {
			type: "string",
			description: "Execute suites in a specified shard",
		},
	}, async args => {
		const { config, logLevel, ...filter } = args;
		if (!args.noLoader) {
			nodeModule.register?.("./loader.js", import.meta.url);
		}
		let cfgObj = await importCWD(config, DEFAULT_CONFIG_FILE);
		cfgObj ??= {};
		if (logLevel) {
			cfgObj.logLevel = logLevel;
		}
		return start(cfgObj, filter);
	});


program.version(false).strict().showHelpOnFail(false).parseAsync();
