name: Sync Mirror

on:
  push:
    branches:
      - master

jobs:
  sync-commits:
    runs-on: ubuntu-latest

    steps:
      - run: gh repo sync Kaciras/ESBench-docs-mirror --force
        env:
          GH_TOKEN: ${{ secrets.MIRROR_PAT }}
