name: Sharding Example

on: [push]

jobs:
  run:
    strategy:
      matrix:
        index: [ 1, 2, 3 ]
        total: [ 3 ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: true

      - run: pnpm run build

      - run: node ../core/lib/host/cli.js --file array- --shared ${{ matrix.index }}/${{ matrix.total }}
        working-directory: example

      - uses: actions/upload-artifact@v4
        with:
          name: result-${{ matrix.index }}.json
          path: example/reports/benchmark.json

  report:
    runs-on: ubuntu-latest
    needs: run

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true

      - run: pnpm run build

      - uses: actions/download-artifact@v4
        with:
          path: example/reports
          pattern: result-*

      - run: node ../core/lib/host/cli.js report reports/**/*.json
        working-directory: example
