name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: true

      - run: pnpm run build
        working-directory: core

      - run: pnpm exec playwright-core install --with-deps
        working-directory: core

      - run: pnpm run test --coverage
        working-directory: core

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
